# Basic Classification with Scikit-Learn

## Load Data and Set Up Training and Testing Data

Import the Pandas and Numpy 

In [2]:
#Import Pandas, Numpy, and Matplotlib Python Libraries
import pandas as pd
import numpy as np

Read the Iris dataset into a Pandas data frame

In [24]:
# iris = pd.read_csv('./datasets/iris.csv')
testing = pd.read_csv("D:\\temp\\IOT_dataset\\CICIoT2023\\part-00000-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv")
# Read all csv files in the CICIoT2023 folder
# import glob
# path = r'D:\\temp\\IOT_dataset\\CICIoT2023'
# all_files = glob.glob(path + "/*.csv")
# li = []
# count = 0
# for filename in all_files:
#     # if we read over 5 files, stop reading files
#     if count > 5:
#         break
#     # # If li goes over 1 GB of memory, stop reading files
#     # if sum([df.memory_usage().sum() for df in li]) > 1e9:
#     #     break
#     df = pd.read_csv(filename, index_col=None, header=0, low_memory=False)
#     li.append(df)
#     count += 1
    
# testing = pd.concat(li, axis=0, ignore_index=True)


View the structure of the Iris data frame

In [25]:
testing

flow_duration  Header_Length  Protocol Type  Duration         Rate  \
0            0.000000          54.00           6.00     64.00     0.329807   
1            0.000000          57.04           6.33     64.00     4.290556   
2            0.000000           0.00           1.00     64.00    33.396799   
3            0.328175       76175.00          17.00     64.00  4642.133010   
4            0.117320         101.73           6.11     65.91     6.202211   
...               ...            ...            ...       ...          ...   
238682       0.000000          54.00           6.00     64.00     3.049186   
238683       0.000000          54.00           6.00     64.00   183.433732   
238684       0.000785          56.29           6.11     64.00   306.952216   
238685       0.000901          72.09           6.11     64.64   158.475986   
238686       0.000000           0.00           1.00     64.00     1.291274   

              Srate  Drate  fin_flag_number  syn_flag_number  rst_flag_number  \
0          0.329807    0.0              1.0              0.0              1.0   
1          4.290556    0.0              0.0              0.0              0.0   
2         33.396799    0.0              0.0              0.0              0.0   
3       4642.133010    0.0              0.0              0.0              0.0   
4          6.202211    0.0              0.0              1.0              0.0   
...             ...    ...              ...              ...              ...   
238682     3.049186    0.0              1.0              0.0              1.0   
238683   183.433732    0.0              0.0              0.0              0.0   
238684   306.952216    0.0              0.0              1.0              0.0   
238685   158.475986    0.0              0.0              0.0              0.0   
238686     1.291274    0.0              0.0              0.0              0.0   

        ...        Std  Tot size           IAT  Number   Magnitue     Radius  \
0       ...   0.000000     54.00  8.334383e+07     9.5  10.392305   0.000000   
1       ...   2.822973     57.04  8.292607e+07     9.5  10.464666   4.010353   
2       ...   0.000000     42.00  8.312799e+07     9.5   9.165151   0.000000   
3       ...   0.000000     50.00  8.301570e+07     9.5  10.000000   0.000000   
4       ...  23.113111     57.88  8.297300e+07     9.5  11.346876  32.716243   
...     ...        ...       ...           ...     ...        ...        ...   
238682  ...   0.000000     54.00  8.334449e+07     9.5  10.392305   0.000000   
238683  ...   0.000000     54.00  8.331392e+07     9.5  10.392305   0.000000   
238684  ...   0.140764     54.21  8.308883e+07     9.5  10.395538   0.200659   
238685  ...   2.450404     55.48  8.333177e+07     9.5  10.456522   3.475801   
238686  ...   0.000000     42.00  8.312453e+07     9.5   9.165151   0.000000   

         Covariance  Variance  Weight              label  
0          0.000000      0.00  141.55   DDoS-RSTFINFlood  
1        160.987842      0.05  141.55      DoS-TCP_Flood  
2          0.000000      0.00  141.55    DDoS-ICMP_Flood  
3          0.000000      0.00  141.55      DoS-UDP_Flood  
4       3016.808286      0.19  141.55      DoS-SYN_Flood  
...             ...       ...     ...                ...  
238682     0.000000      0.00  141.55   DDoS-RSTFINFlood  
238683     0.000000      0.00  141.55  DDoS-PSHACK_Flood  
238684     0.671167      0.03  141.55     DDoS-SYN_Flood  
238685    55.994224      0.17  141.55  DDoS-PSHACK_Flood  
238686     0.000000      0.00  141.55    DDoS-ICMP_Flood  

[238687 rows x 47 columns]

Use the hold out method to create training data (70% random sample) and testing data (30% random sample)

In [26]:
# Split the data into training and testing sets
train=testing.sample(frac=0.7,random_state=1234) # random state is a seed value, so that the same sample is selected each time
test=testing.drop(train.index) # drop the rows that are in the training set, so that the test set is disjoint

In [27]:
# Get the headers of the columns
headers = list(testing.columns)
# Remove the 'label' column
headers.remove('label')

Separate the observations from the class/target variable in both the training and testing data.  Use the ravel() function to flatten the 1D array for the class variable.  This is necessary for some of methods used to classify and assess accuracy.

In [28]:

obs = headers
cls = ['label']
trainObs = train[obs].to_numpy()            # TrainObs: The features for the training data as an array
trainCls = train[cls].to_numpy().ravel()    # TrainCls: The labels for the training data as an array
testObs = test[obs].to_numpy()              # TestObs: The features for the test data as an array
testCls = test[cls].to_numpy().ravel()      # TestCls: The labels for the test data as an array

In [30]:
# Rescale the data to be between 0 and 1
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaler.fit(trainObs)
trainObs = scaler.transform(trainObs)
testObs = scaler.transform(testObs)

## K Nearest Neighbor Classification

Set up a K Nearest Neighbor Classifier with the number of neighbors = 3 and weights based on Euclidean distance

In [31]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=4, weights='distance')

Fit the K Nearest Neighbor classifier to the training data and use the resulting classifier to predict the class values for the test dataset

In [32]:
# Train the classifier on our training data
knn.fit(trainObs, trainCls)
# Predict the labels for the test data
knn_pred = knn.predict(testObs)

Calculate the accuracy of the classifier.

In [33]:
from __future__ import division
(sum(testCls==knn_pred))/len(knn_pred)

0.9364578387285981

Create a confusion matrix using Scikit-Learn confusion_matrix

In [34]:
# Get all the unique labels within the label column
labels = testing['label'].unique()
labels

array(['DDoS-RSTFINFlood', 'DoS-TCP_Flood', 'DDoS-ICMP_Flood',
       'DoS-UDP_Flood', 'DoS-SYN_Flood', 'Mirai-greeth_flood',
       'DDoS-SynonymousIP_Flood', 'Mirai-udpplain', 'DDoS-SYN_Flood',
       'DDoS-PSHACK_Flood', 'DDoS-TCP_Flood', 'DDoS-UDP_Flood',
       'BenignTraffic', 'MITM-ArpSpoofing', 'DDoS-ACK_Fragmentation',
       'Mirai-greip_flood', 'DoS-HTTP_Flood', 'DDoS-ICMP_Fragmentation',
       'Recon-PortScan', 'DNS_Spoofing', 'DDoS-UDP_Fragmentation',
       'Recon-OSScan', 'XSS', 'DDoS-HTTP_Flood', 'Recon-HostDiscovery',
       'CommandInjection', 'VulnerabilityScan', 'DDoS-SlowLoris',
       'Backdoor_Malware', 'BrowserHijacking', 'DictionaryBruteForce',
       'SqlInjection', 'Recon-PingSweep', 'Uploading_Attack'],
      dtype=object)

In [35]:
from sklearn.metrics import confusion_matrix
knn_tab = confusion_matrix(testCls, knn_pred, labels=(labels))
knn_tab

array([[ 6267,     0,     0, ...,     0,     0,     0],
       [    0,  3735,     0, ...,     0,     0,     0],
       [    0,     0, 10930, ...,     0,     0,     0],
       ...,
       [    0,     0,     0, ...,     0,     0,     0],
       [    0,     0,     0, ...,     0,     0,     0],
       [    0,     0,     0, ...,     0,     0,     0]], dtype=int64)

Create a classification report for the result including precision, recall, and f measure.

In [37]:
from sklearn import metrics
print(metrics.classification_report(testCls, knn_pred))

c:\Users\molin\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\molin\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


                         precision    recall  f1-score   support

       Backdoor_Malware       0.00      0.00      0.00         6
          BenignTraffic       0.75      0.87      0.80      1668
       BrowserHijacking       0.00      0.00      0.00        15
       CommandInjection       0.00      0.00      0.00        10
 DDoS-ACK_Fragmentation       0.98      0.98      0.98       446
        DDoS-HTTP_Flood       0.67      0.57      0.62        58
        DDoS-ICMP_Flood       1.00      1.00      1.00     10942
DDoS-ICMP_Fragmentation       0.98      0.98      0.98       733
      DDoS-PSHACK_Flood       1.00      1.00      1.00      6337
       DDoS-RSTFINFlood       1.00      1.00      1.00      6269
         DDoS-SYN_Flood       0.92      0.95      0.93      6243
         DDoS-SlowLoris       0.60      0.50      0.55        30
DDoS-SynonymousIP_Flood       0.96      0.95      0.95      5370
         DDoS-TCP_Flood       0.94      0.95      0.95      6958
         DDoS-UDP_Flood 

c:\Users\molin\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Exercise 1: Now go back and experiment with different values of k.  What happened?

## Decision Tree Classification

Create a decision tree classifier and fit it to the training dataset.  This Scikit-Learn decision tree is based on the CART algorithm.  The default parameters use the GINI index as the metric for finding the best attribute split.

In [38]:
from sklearn import tree
clf = tree.DecisionTreeClassifier()
clf = clf.fit(trainObs, trainCls)

Export the resulting tree in GraphVis format.  You can open the resulting file "tree.dot" in the graphviz Python library or at the graphviz website located at: http://www.webgraphviz.com/

In [39]:
tree.export_graphviz(clf, out_file='tree.dot', feature_names= headers,  
                         class_names=labels,)   

In [40]:
dt_pred = clf.predict(testObs)
sum(testCls==dt_pred)/len(dt_pred)

0.9914392648660727

Exercise 2: Use the evaluation metric code from the KNN example to assess the quality of your decision tree classifier.  Did you find any differences?

You can also use a measure of entropy as the split criteria by including the parameter criterion="entropy".

In [41]:
clf = tree.DecisionTreeClassifier(criterion="entropy")
clf = clf.fit(trainObs, trainCls)
dt_pred = clf.predict(testObs)
sum(testCls==dt_pred)/len(dt_pred)

0.9916766751389549

## Random Forest Classifier

Set up a random forest classifier with the number of estimators (trees) = 10

In [42]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_estimators=10)
clf = clf.fit(trainObs, trainCls)

In [43]:
rf_pred = clf.predict(testObs)
sum(testCls==rf_pred)/len(rf_pred)

0.9888696477948775

Exercise 3: Assess the quality of your random forest classifier.  What did you find?  Now change the n_estimators parameter to 100, 1000, and 10,000.  What happened?

## Naive Bayes Classifier

Create a Naive Bayes classifier

In [44]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb = gnb.fit(trainObs, trainCls)

In [45]:
nb_pred = gnb.predict(testObs)
sum(testCls==nb_pred)/len(nb_pred)

0.6281596514258582

# Classification - More Models and Ideas

## Load Data and Set Up Training and Testing Data

Read the breast cancer dataset from SciKits Learn datasets

In [35]:
# from sklearn.datasets import load_breast_cancer
# cancer = load_breast_cancer()

Set X = the attributes and y = the target variable

In [54]:
X = testing[obs]
Y = testing[cls]
Y = Y.values.ravel()


Use train_test_split to split the data into training and testing sets

In [55]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y)

Rescale the data to values between 1 and 0 (this gives each attribute equal weight)

In [56]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
# Fit only to the training data
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

## Logistic Regression

Set up the logistic regression classifier with 

In [57]:
from sklearn import linear_model
logreg = linear_model.LogisticRegression(C=1e5, max_iter=10000)

Fit the logistic regression model to the training data and use the resulting classifier to predict the class values for the test dataset

In [58]:
logreg.fit(X_train, y_train)
logreg_pred = logreg.predict(X_test)
logreg

c:\Users\molin\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(C=100000.0)

Calculate the accuracy of the classifier.

In [41]:
from __future__ import division
(sum(y_test==logreg_pred))/len(logreg_pred)

0.9020979020979021

Create a confusion matrix using Scikit-Learn confusion_matrix

In [42]:
from sklearn.metrics import confusion_matrix
logreg_tab = confusion_matrix(y_test, logreg_pred)
logreg_tab

array([[49,  4],
       [10, 80]], dtype=int64)

Create a classification report for the result including precision, recall, and f measure.

In [43]:
from sklearn import metrics
print(metrics.classification_report(y_test, logreg_pred))

              precision    recall  f1-score   support

           0       0.83      0.92      0.88        53
           1       0.95      0.89      0.92        90

    accuracy                           0.90       143
   macro avg       0.89      0.91      0.90       143
weighted avg       0.91      0.90      0.90       143



## Neural Networks

Create a multilayer perceptron classifier and fit it to the training dataset.  The classifier will use the 

In [44]:
from sklearn.neural_network import MLPClassifier
mlp = MLPClassifier(solver='sgd', hidden_layer_sizes=(30,30,30))
mlp.fit(X_train,y_train)

c:\Users\molin\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPClassifier(hidden_layer_sizes=(30, 30, 30), solver='sgd')

Use the neural network to predict the test set and calculate the accuracy.

In [45]:
from __future__ import division
mlp_pred = mlp.predict(X_test)
(sum(y_test==mlp_pred))/len(mlp_pred)

0.958041958041958

In [46]:
print(confusion_matrix(y_test,mlp_pred))

[[50  3]
 [ 3 87]]


Now try a different solver.  Did you get different results?

In [47]:
from sklearn.neural_network import MLPClassifier
mlp = MLPClassifier(solver='lbfgs', hidden_layer_sizes=(30,30,30))
mlp.fit(X_train,y_train)

MLPClassifier(hidden_layer_sizes=(30, 30, 30), solver='lbfgs')

## Support Vector Machines

Set up a SVM classifier using the radial basis function kernel

In [48]:
from sklearn import svm
svm_clf = svm.SVC(kernel="rbf")
svm_clf.fit(X_train,y_train)

SVC()

In [49]:
svm_pred = svm_clf.predict(X_test)
print(confusion_matrix(y_test,svm_pred))

[[50  3]
 [ 2 88]]


## Ensemble Methods

Bagging

In [ ]:
from sklearn.ensemble import BaggingClassifier
from sklearn.naive_bayes import GaussianNB
bagging = BaggingClassifier(GaussianNB(), max_samples=0.5, max_features=0.5)
bagging.fit(X_train,y_train)

In [ ]:
bag_pred = bagging.predict(X_test)
print(confusion_matrix(y_test,bag_pred))

Use cross validation to find the overall accuracy of the bagged classifier

In [ ]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(bagging, X, y)
scores.mean()

Boosting

In [ ]:
from sklearn.ensemble import AdaBoostClassifier
boosting = AdaBoostClassifier(n_estimators=100)
boosting.fit(X_train, y_train)
boost_pred = boosting.predict(X_test)
print(confusion_matrix(y_test, boost_pred))                     

Use cross validation to find the overall accuracy of the boosted classifier

In [ ]:
scores = cross_val_score(boosting, X, y)
scores.mean()

## Cross Validation Sampling

K-fold Cross Validation Sample

In [ ]:
from sklearn.model_selection import KFold
from sklearn import svm
svm_clf = svm.SVC(kernel="rbf")
kf = KFold(n_splits=10)
kf.get_n_splits(X)
for train_index, test_index in kf.split(X):
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    svm_clf.fit(X_train,y_train)
    svm_pred = svm_clf.predict(X_test)
    print((sum(y_test==svm_pred))/len(svm_pred))

Exercise 4: Assess the quality of your Naive Bayes classifer.  How does it compare?

# My Own Testing Of Scikit

In [53]:
from sklearn import datasets

i = datasets.load_iris()
digits = datasets.load_digits()
digits.images[0]

array([[ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.],
       [ 0.,  0., 13., 15., 10., 15.,  5.,  0.],
       [ 0.,  3., 15.,  2.,  0., 11.,  8.,  0.],
       [ 0.,  4., 12.,  0.,  0.,  8.,  8.,  0.],
       [ 0.,  5.,  8.,  0.,  0.,  9.,  8.,  0.],
       [ 0.,  4., 11.,  0.,  1., 12.,  7.,  0.],
       [ 0.,  2., 14.,  5., 10., 12.,  0.,  0.],
       [ 0.,  0.,  6., 13., 10.,  0.,  0.,  0.]])

In [54]:
from sklearn import svm
clf = svm.SVC(gamma=0.001, C=100.)
# Pass all but the last element of the array as data, for the estimator to learn, and the last element as the target
clf.fit(digits.data[:-1], digits.target[:-1])

SVC(C=100.0, gamma=0.001)

In [56]:
print(digits.data[-1:])
clf.predict(digits.data[-1:])

[[ 0.  0. 10. 14.  8.  1.  0.  0.  0.  2. 16. 14.  6.  1.  0.  0.  0.  0.
  15. 15.  8. 15.  0.  0.  0.  0.  5. 16. 16. 10.  0.  0.  0.  0. 12. 15.
  15. 12.  0.  0.  0.  4. 16.  6.  4. 16.  6.  0.  0.  8. 16. 10.  8. 16.
   8.  0.  0.  1.  8. 12. 14. 12.  1.  0.]]


array([8])