In [21]:
from sklearn.cluster import KMeans

import numpy as np

X = np.array([
    [2, 10],
    [2, 5],
    [8, 4],
    [5, 8],
    [7, 5],
    [6, 4],
    [1, 2],
    [4, 9]
])

kmeans = KMeans(n_clusters=3, random_state=0, init=np.array([[2,10], [5,8], [1,2]]), max_iter=300, n_init=1).fit(X)

In [22]:
kmeans.labels_

array([0, 2, 1, 0, 1, 1, 2, 0])

In [23]:
kmeans.cluster_centers_

array([[3.66666667, 9.        ],
       [7.        , 4.33333333],
       [1.5       , 3.5       ]])

In [25]:
max_iter = kmeans.n_iter_
max_iter

4

### View Each Cluster After Every Iteration

In [28]:
for i in range(1, max_iter+1):
    kmeans = KMeans(n_clusters=3, random_state=0, init=np.array([[2,10], [5,8], [1,2]]), max_iter=i, n_init=1).fit(X)
    print("============== Iteration {} ==============".format(i))
    centers = kmeans.cluster_centers_
    for j in range(0, len(centers)):
        print("Cluster {}: {}".format(j+1, centers[j]))

============== Iteration 1 ==============
Cluster 1: [ 2. 10.]
Cluster 2: [6. 6.]
Cluster 3: [1.5 3.5]
============== Iteration 2 ==============
Cluster 1: [3.  9.5]
Cluster 2: [6.5  5.25]
Cluster 3: [1.5 3.5]
============== Iteration 3 ==============
Cluster 1: [3.66666667 9.        ]
Cluster 2: [7.         4.33333333]
Cluster 3: [1.5 3.5]
============== Iteration 4 ==============
Cluster 1: [3.66666667 9.        ]
Cluster 2: [7.         4.33333333]
Cluster 3: [1.5 3.5]


### View Centers After Changing Initial Centers

In [18]:
kmeans = KMeans(n_clusters=3, random_state=0, init=np.array([[8, 4], [7,5], [6, 4]])).fit(X)

c:\Users\molin\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\cluster\_kmeans.py:1416: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)
c:\Users\molin\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\cluster\_kmeans.py:1416: RuntimeWarning: Explicit initial center position passed: performing only one init in KMeans instead of n_init=10.
  super()._check_params_vs_input(X, default_n_init=10)


In [19]:
kmeans.cluster_centers_

array([[7.        , 4.33333333],
       [3.66666667, 9.        ],
       [1.5       , 3.5       ]])